### ISSUE TITLE
Files using DOS line endings

### ISSUE THREAD

**Issue by bricas** [usask-library/ezproxy-stanzas#1]
```
> find . -not -type d -exec file "{}" ";" | grep CRLF
./OCLC/Chadwyck_Databases.txt: ASCII text, with CRLF line terminators
./OCLC/BioMed_Central.txt: ASCII text, with CRLF line terminators
./OCLC/Wiley_Online_Library.txt: ASCII text, with CRLF line terminators
```

It's a minor thing, but easily fixed.

**Comment by g011um** [comment]
Thanks for catching this Brian.  I've added some dos2unix magic to my processing scripts so hopefully this won't be an issue again.

**Comment by bricas** [comment]
Heya! Seems like the changes didn't stick. I'm seeing CRLFs in those same 3 files again.
